"""Seed complaints: realistic, Urdu-influenced English, spread across categories.
Each tuple is (seed_key, text, location, reporter_contact, status)."""

SEED_COMPLAINTS: list[tuple[str, str, str, str | None, str]] = [
    (
        "w01",
        "Burst water main flooding Street 12 since fajr, water entering ground floors. Please send team fori.",
        "Street 12, G-9/2, Islamabad",
        "0300-1234567",
        "open",
    ),
    (
        "w02",
        "Paani nahi aa raha for 3 days in our lane. Tanker wala asking Rs 4000, we cannot afford daily.",
        "Lane 4, I-8/4, Islamabad",
        None,
        "in_progress",
    ),
    (
        "w03",
        "Pipe leak near the masjid, clean water wasting on the road since morning. Road also getting kharab.",
        "Near Jamia Masjid, F-7/3, Islamabad",
        "0312-5550001",
        "open",
    ),
    (
        "w04",
        "Water supply line brown and smelly, bachay beemar ho rahe hain. Please test the water.",
        "Block C, Satellite Town, Rawalpindi",
        None,
        "open",
    ),
    (
        "w05",
        "Low water pressure in upper portion since last week, motor bhi kaam nahi kar raha.",
        "House 22, G-10/1, Islamabad",
        "0333-7771122",
        "resolved",
    ),
    (
        "w06",
        "Tap water supply timing changed without notice, please share the new schedule.",
        "Street 7, G-11/3, Islamabad",
        None,
        "rejected",
    ),
    (
        "e01",
        "Live wire hanging from the pole after the storm, sparks coming. Children play here, khatra hai.",
        "Street 3, F-10/2, Islamabad",
        "0321-9998877",
        "open",
    ),
    (
        "e02",
        "Bijli gayi hui hai since 11 pm, whole block in darkness and transformer making noise.",
        "Block B, Saddar, Rawalpindi",
        None,
        "in_progress",
    ),
    (
        "e03",
        "Load shedding schedule is 6 hours but we are getting 10 hours outage daily. Elderly people suffering in heat.",
        "Chaklala Scheme 3, Rawalpindi",
        "0345-1112233",
        "open",
    ),
    (
        "e04",
        "Voltage very low in the evening, fridge and AC not working properly.",
        "Street 15, I-10/2, Islamabad",
        None,
        "open",
    ),
    (
        "e05",
        "Transformer caught fire last night, aag lag gayi thi, fire brigade came but no repair yet.",
        "Main Double Road, G-13/1, Islamabad",
        "0301-4445566",
        "in_progress",
    ),
    (
        "e06",
        "Electricity meter showing wrong reading, bill too high this month.",
        "House 5, Street 9, E-11/3, Islamabad",
        "0302-6667788",
        "rejected",
    ),
    (
        "s01",
        "Kachra not collected for two weeks, badboo everywhere and mosquitoes breeding.",
        "Street 18, G-6/1, Islamabad",
        None,
        "open",
    ),
    (
        "s02",
        "Sewage overflowing into homes from the gutter line, ghar mein ganda pani aa raha hai.",
        "Dhok Hassu, Rawalpindi",
        "0311-2223344",
        "open",
    ),
    (
        "s03",
        "Open nala near the school is blocked, smell is unbearable and children fall sick.",
        "Near Govt School, Sadiqabad, Rawalpindi",
        None,
        "in_progress",
    ),
    (
        "s04",
        "Garbage dump next to the park, people burning the waste every evening.",
        "Park Road, F-8/4, Islamabad",
        "0334-8889900",
        "open",
    ),
    (
        "s05",
        "Drain cover missing on the footpath, someone can fall in at night.",
        "Jinnah Avenue, Blue Area, Islamabad",
        None,
        "resolved",
    ),
    (
        "s06",
        "Machar bohat zyada hain, please arrange spray in our sector.",
        "Sector G-7/2, Islamabad",
        None,
        "open",
    ),
    (
        "r01",
        "Huge gaddha in the middle of the road, two motorcycle accidents this week, one person injured.",
        "Murree Road near Committee Chowk, Rawalpindi",
        "0300-3332211",
        "open",
    ),
    (
        "r02",
        "Road carpeting left half done for 3 months, dust everywhere and traffic jam daily.",
        "Service Road, I-9/4, Islamabad",
        None,
        "in_progress",
    ),
    (
        "r03",
        "Speed breaker has no paint, cars keep hitting it at night.",
        "Street 40, G-9/4, Islamabad",
        None,
        "open",
    ),
    (
        "r04",
        "Footpath broken near the bus stop, elderly people cannot walk safely.",
        "Peshawar Road, Rawalpindi",
        "0315-6665544",
        "open",
    ),
    (
        "r05",
        "Sadak dhans gayi hai after rain, part of road collapsed near the nala.",
        "Lai Nala Bridge, Rawalpindi",
        None,
        "open",
    ),
    (
        "r06",
        "Road name board faded, visitors cannot find the street. Minor request.",
        "Street 2, F-6/3, Islamabad",
        None,
        "resolved",
    ),
    (
        "l01",
        "All street lights off in our lane for a week, andhera hai and there were two snatching incidents.",
        "Lane 6, G-11/2, Islamabad",
        "0331-1212121",
        "open",
    ),
    (
        "l02",
        "Streetlight flickering all night outside house 14.",
        "Street 21, F-11/1, Islamabad",
        None,
        "open",
    ),
    (
        "l03",
        "Khamba light is on during the day and off at night, timer seems broken.",
        "Street 1, I-8/3, Islamabad",
        None,
        "in_progress",
    ),
    (
        "l04",
        "Street lights on the main boulevard are very dim, please replace with LED.",
        "Main Boulevard, DHA Phase 2, Islamabad",
        "0322-4343434",
        "open",
    ),
    (
        "l05",
        "Lamp post leaning dangerously after the truck hit it, may fall on the road.",
        "Street 9, G-8/1, Islamabad",
        None,
        "open",
    ),
    (
        "o01",
        "Stray dogs in the street chasing children in the evening, please take action.",
        "Street 30, G-10/4, Islamabad",
        "0300-9090909",
        "open",
    ),
    (
        "o02",
        "Loud wedding music till 3 am every weekend in the community hall.",
        "Community Center, F-10/4, Islamabad",
        None,
        "rejected",
    ),
    (
        "o03",
        "Park swings are broken and the grass has not been cut for months.",
        "Fatima Jinnah Park area, F-9, Islamabad",
        None,
        "open",
    ),
    (
        "o04",
        "Illegal encroachment by shopkeepers on the service lane, cars cannot pass.",
        "Commercial Market, Satellite Town, Rawalpindi",
        "0313-5656565",
        "in_progress",
    ),
    (
        "o05",
        "Request to install a bench at the bus stop for elderly passengers.",
        "Faizabad Bus Stop, Rawalpindi",
        None,
        "open",
    ),
]
